### ISSUE TITLE
No data in kube-ui when not running kube master

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kube-ui#54]
#### 1. Create kube-system namespace yaml file,

```
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system

```
#### 2. Create kube-system namespace by running the command below

```
kubectl create -f kube-system.yml
kubectl get namespace
```
#### 3. Label the kubernetes nodes for cluster management, and find nodes by label

```
kubectl label nodes abcd-x kube-system=true

kubectl get nodes -l kube-system=true -o=wide
```
##### 4.1 Create kube-ui-svc.yml

```
apiVersion: v1
kind: Service
metadata:
  name: kube-ui
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeUI"
spec:
  selector:
    k8s-app: kube-ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
```
##### 4.2 Deploy kube-ui service

```
# kubectl create -f kube-ui-svc.yml
# kubectl get svc --all-namespaces
```
##### 5.1 Create kube-ui-rc.yml

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-ui-v2
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    version: v2
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-ui
    version: v2
  template:
    metadata:
      labels:
        k8s-app: kube-ui
        version: v2
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-ui
        image: gcr.io/google_containers/kube-ui:v2
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
      nodeSelector:
        kube-system: "true"
```
##### 5.2 Deploy kube-ui rc

```
# kubectl create -f kube-ui-rc.yml
# kubectl get rc,pods --all-namespaces
```
#### 6. Access kube-ui for checking cluster's status

```
http://abcd-x:30080/#/dashboard/pods
```

But there is no data showed in UI.
I am using k8s 1.2, I am wondering if there is any way to make it work by using nodeport rather than master ip. Or I'm wondering is if there is any way to set kube-api server's ip address and port?

 It can work if I configured master routable to the pod(flanneld) and access http://{kube-master}:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/. But I want to know if I don't want to run flanneld in kube-master, is there any way to use kube-ui as well?
